### PR TITLE
Bump up Node.js version to 16 and upgrade version of actions/setup-node@v1

### PR DESCRIPTION
**Pull request by chotgor1**
## What it is
- Bump up Node.js version to 16 
- Upgrade version of actions/setup-node@v1 to v3

### CODE REVIEW

**Comment by slashformotion** [comment]
looks like your PR is more complete, I will remove mine

**Comment by rburgstaller** [comment]
@deepakputhraya can we get this merged?

**Comment by fbuinosquy1985** [comment]
need this

**Comment by fbuinosquy1985** [comment]
@deepakputhraya can we get this merged?

**Comment by slashformotion** [comment]
@deepakputhraya  can we get this merged?

**Comment by tatagaziz** [comment]
@deepakputhraya can we please reopen and merge this PR?

**Pull request closed without merging**
